name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive
        
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential cmake libgtest-dev googletest

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build
      
    - name: Build
      run: cmake --build ${{github.workspace}}/build

    - name: Run Basic Demo
      working-directory: ${{github.workspace}}/build
      run: ./demo_basic

    - name: Run Advanced Demo
      working-directory: ${{github.workspace}}/build
      run: ./demo_advanced

    - name: Run Unit Tests
      working-directory: ${{github.workspace}}/build
      run: ./ConcurrentHashMapTest

  test:
      name: Run tests and collect coverage
      runs-on: ubuntu-latest
      steps:
        - name: Checkout
          uses: actions/checkout@v4
          with:
            fetch-depth: 2
  
        - name: Set up Node
          uses: actions/setup-node@v4
  
        - name: Install dependencies
          run: npm install
  
        - name: Run tests
          run: npx jest --coverage
  
        - name: Upload results to Codecov
          uses: codecov/codecov-action@v5
          with:
            token: ${{ secrets.CODECOV_TOKEN }}
            slug: diffstorm/ConcurrentHashMap
